<?php
define("HOST","localhost");
define("USER","grupo1");
define("PORT","5432");
define("PASSWORD","grupo1");
define("DATABASE","grupo1");
define("MONGO_DATABASE",'test');
/*
/*
define("cursos",'cursos');
define("universidades",'universidades');
define("alumnos",'alumnos');
*/
?>
